version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - npm run-script lint
      - npm test
      - serverless deploy --stage production --region eu-central-1
   #   - serverless deploy --stage dev -v
#       - npm run-script integration
#   post_build:
#     commands:
#       - serverless remove --stage test -v
